# Generated by Django 5.0.6 on 2024-07-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unique_application_numbers', models.IntegerField()),
                ('unique_duplicate_numbers', models.IntegerField()),
                ('unique_add_status_numbers', models.IntegerField()),
                ('unique_extension_numbers', models.IntegerField()),
                ('processing_complete_numbers', models.IntegerField()),
                ('returned_for_clarification_status_numbers', models.IntegerField()),
                ('sent_for_processing_status_numbers', models.IntegerField()),
                ('unique_id_packages', models.IntegerField()),
                ('unique_request_author', models.IntegerField()),
            ],
        ),
    ]
