# Generated by Django 5.0.6 on 2024-07-08 20:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_data_processing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationdata',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='applicationdata',
            name='file_name',
        ),
        migrations.AddField(
            model_name='applicationdata',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
