# Generated by Django 5.0.6 on 2024-07-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_data_processing', '0002_rename_created_at_applicationdata_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdata',
            name='processing_complete_numbers',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='applicationdata',
            name='returned_for_clarification_status_numbers',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='applicationdata',
            name='sent_for_processing_status_numbers',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='applicationdata',
            name='unique_add_status_numbers',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='applicationdata',
            name='unique_application_numbers',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='applicationdata',
            name='unique_duplicate_numbers',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='applicationdata',
            name='unique_extension_numbers',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='applicationdata',
            name='unique_id_packages',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='applicationdata',
            name='unique_request_author',
            field=models.IntegerField(null=True),
        ),
    ]
